const deleteBotFromGroup = {
  update: {
    update_id: 9214907,
    my_chat_member: {
      chat: {
        id: -4896561350,
        title: "Test group",
        type: "group",
        all_members_are_administrators: true,
        accepted_gift_types: {
          unlimited_gifts: false,
          limited_gifts: false,
          unique_gifts: false,
          premium_subscription: false,
        },
      },
      from: {
        id: 886363509,
        is_bot: false,
        first_name: "Вадим",
        last_name: "Безсмертний",
        username: "VadymBezsmertnyi",
        language_code: "uk",
      },
      date: 1754927040,
      old_chat_member: {
        user: {
          id: 7691627975,
          is_bot: true,
          first_name: "TeleGate Auth Bot",
          username: "TeleGateAuthBot",
        },
        status: "member",
      },
      new_chat_member: {
        user: {
          id: 7691627975,
          is_bot: true,
          first_name: "TeleGate Auth Bot",
          username: "TeleGateAuthBot",
        },
        status: "left",
      },
    },
  },
  telegram: {
    token: "",
    options: {
      apiRoot: "https://api.telegram.org",
      apiMode: "bot",
      webhookReply: true,
      agent: {
        _events: {},
        _eventsCount: 2,
        defaultPort: 443,
        protocol: "https:",
        options: {
          keepAlive: true,
          keepAliveMsecs: 10000,
          noDelay: true,
          path: null,
        },
        requests: {},
        sockets: {},
        keepAliveMsecs: 10000,
        keepAlive: true,
        maxSockets: null,
        maxFreeSockets: 256,
        scheduling: "lifo",
        maxTotalSockets: null,
        totalSocketCount: 1,
        maxCachedSessions: 100,
      },
      testEnv: false,
    },
  },
  botInfo: {
    id: 7691627975,
    is_bot: true,
    first_name: "TeleGate Auth Bot",
    username: "TeleGateAuthBot",
    can_join_groups: true,
    can_read_all_group_messages: true,
    supports_inline_queries: false,
    can_connect_to_business: false,
    has_main_web_app: false,
  },
  state: {},
};

const deleteBotFromGroupMessage = {
  update: {
    update_id: 9214908,
    message: {
      message_id: 16,
      from: {
        id: 886363509,
        is_bot: false,
        first_name: "Вадим",
        last_name: "Безсмертний",
        username: "VadymBezsmertnyi",
        language_code: "uk",
      },
      chat: {
        id: -4896561350,
        title: "Test group",
        type: "group",
        all_members_are_administrators: true,
        accepted_gift_types: {
          unlimited_gifts: false,
          limited_gifts: false,
          unique_gifts: false,
          premium_subscription: false,
        },
      },
      date: 1754927040,
      left_chat_participant: {
        id: 7691627975,
        is_bot: true,
        first_name: "TeleGate Auth Bot",
        username: "TeleGateAuthBot",
      },
      left_chat_member: {
        id: 7691627975,
        is_bot: true,
        first_name: "TeleGate Auth Bot",
        username: "TeleGateAuthBot",
      },
    },
  },
  telegram: {
    token: "",
    options: {
      apiRoot: "https://api.telegram.org",
      apiMode: "bot",
      webhookReply: true,
      agent: {
        _events: {},
        _eventsCount: 2,
        defaultPort: 443,
        protocol: "https:",
        options: {
          keepAlive: true,
          keepAliveMsecs: 10000,
          noDelay: true,
          path: null,
        },
        requests: {},
        sockets: {},
        keepAliveMsecs: 10000,
        keepAlive: true,
        maxSockets: null,
        maxFreeSockets: 256,
        scheduling: "lifo",
        maxTotalSockets: null,
        totalSocketCount: 1,
        maxCachedSessions: 100,
      },
      testEnv: false,
    },
  },
  botInfo: {
    id: 7691627975,
    is_bot: true,
    first_name: "TeleGate Auth Bot",
    username: "TeleGateAuthBot",
    can_join_groups: true,
    can_read_all_group_messages: true,
    supports_inline_queries: false,
    can_connect_to_business: false,
    has_main_web_app: false,
  },
  state: {},
};

const addBotToGroup = {
  update: {
    update_id: 9214909,
    my_chat_member: {
      chat: {
        id: -4896561350,
        title: "Test group",
        type: "group",
        all_members_are_administrators: true,
        accepted_gift_types: {
          unlimited_gifts: false,
          limited_gifts: false,
          unique_gifts: false,
          premium_subscription: false,
        },
      },
      from: {
        id: 886363509,
        is_bot: false,
        first_name: "Вадим",
        last_name: "Безсмертний",
        username: "VadymBezsmertnyi",
        language_code: "uk",
      },
      date: 1754927273,
      old_chat_member: {
        user: {
          id: 7691627975,
          is_bot: true,
          first_name: "TeleGate Auth Bot",
          username: "TeleGateAuthBot",
        },
        status: "left",
      },
      new_chat_member: {
        user: {
          id: 7691627975,
          is_bot: true,
          first_name: "TeleGate Auth Bot",
          username: "TeleGateAuthBot",
        },
        status: "member",
      },
    },
  },
  telegram: {
    token: "",
    options: {
      apiRoot: "https://api.telegram.org",
      apiMode: "bot",
      webhookReply: true,
      agent: {
        _events: {},
        _eventsCount: 2,
        defaultPort: 443,
        protocol: "https:",
        options: {
          keepAlive: true,
          keepAliveMsecs: 10000,
          noDelay: true,
          path: null,
        },
        requests: {},
        sockets: {},
        keepAliveMsecs: 10000,
        keepAlive: true,
        maxSockets: null,
        maxFreeSockets: 256,
        scheduling: "lifo",
        maxTotalSockets: null,
        totalSocketCount: 1,
        maxCachedSessions: 100,
      },
      testEnv: false,
    },
  },
  botInfo: {
    id: 7691627975,
    is_bot: true,
    first_name: "TeleGate Auth Bot",
    username: "TeleGateAuthBot",
    can_join_groups: true,
    can_read_all_group_messages: true,
    supports_inline_queries: false,
    can_connect_to_business: false,
    has_main_web_app: false,
  },
  state: {},
};

const botAddedToGroupMessage = {
  update: {
    update_id: 9214910,
    message: {
      message_id: 17,
      from: {
        id: 886363509,
        is_bot: false,
        first_name: "Вадим",
        last_name: "Безсмертний",
        username: "VadymBezsmertnyi",
        language_code: "uk",
      },
      chat: {
        id: -4896561350,
        title: "Test group",
        type: "group",
        all_members_are_administrators: true,
        accepted_gift_types: {
          unlimited_gifts: false,
          limited_gifts: false,
          unique_gifts: false,
          premium_subscription: false,
        },
      },
      date: 1754927273,
      new_chat_participant: {
        id: 7691627975,
        is_bot: true,
        first_name: "TeleGate Auth Bot",
        username: "TeleGateAuthBot",
      },
      new_chat_member: {
        id: 7691627975,
        is_bot: true,
        first_name: "TeleGate Auth Bot",
        username: "TeleGateAuthBot",
      },
      new_chat_members: [
        {
          id: 7691627975,
          is_bot: true,
          first_name: "TeleGate Auth Bot",
          username: "TeleGateAuthBot",
        },
      ],
    },
  },
  telegram: {
    token: "",
    options: {
      apiRoot: "https://api.telegram.org",
      apiMode: "bot",
      webhookReply: true,
      agent: {
        _events: {},
        _eventsCount: 2,
        defaultPort: 443,
        protocol: "https:",
        options: {
          keepAlive: true,
          keepAliveMsecs: 10000,
          noDelay: true,
          path: null,
        },
        requests: {},
        sockets: {},
        keepAliveMsecs: 10000,
        keepAlive: true,
        maxSockets: null,
        maxFreeSockets: 256,
        scheduling: "lifo",
        maxTotalSockets: null,
        totalSocketCount: 1,
        maxCachedSessions: 100,
      },
      testEnv: false,
    },
  },
  botInfo: {
    id: 7691627975,
    is_bot: true,
    first_name: "TeleGate Auth Bot",
    username: "TeleGateAuthBot",
    can_join_groups: true,
    can_read_all_group_messages: true,
    supports_inline_queries: false,
    can_connect_to_business: false,
    has_main_web_app: false,
  },
  state: {},
};

const classicMessage = {
  update: {
    update_id: 9214911,
    message: {
      message_id: 19,
      from: {
        id: 886363509,
        is_bot: false,
        first_name: "Вадим",
        last_name: "Безсмертний",
        username: "VadymBezsmertnyi",
        language_code: "uk",
      },
      chat: {
        id: -4896561350,
        title: "Test group",
        type: "group",
        all_members_are_administrators: true,
        accepted_gift_types: {
          unlimited_gifts: false,
          limited_gifts: false,
          unique_gifts: false,
          premium_subscription: false,
        },
      },
      date: 1754927360,
      text: "Test",
    },
  },
  telegram: {
    token: "",
    options: {
      apiRoot: "https://api.telegram.org",
      apiMode: "bot",
      webhookReply: true,
      agent: {
        _events: {},
        _eventsCount: 2,
        defaultPort: 443,
        protocol: "https:",
        options: {
          keepAlive: true,
          keepAliveMsecs: 10000,
          noDelay: true,
          path: null,
        },
        requests: {},
        sockets: {},
        keepAliveMsecs: 10000,
        keepAlive: true,
        maxSockets: null,
        maxFreeSockets: 256,
        scheduling: "lifo",
        maxTotalSockets: null,
        totalSocketCount: 1,
        maxCachedSessions: 100,
      },
      testEnv: false,
    },
  },
  botInfo: {
    id: 7691627975,
    is_bot: true,
    first_name: "TeleGate Auth Bot",
    username: "TeleGateAuthBot",
    can_join_groups: true,
    can_read_all_group_messages: true,
    supports_inline_queries: false,
    can_connect_to_business: false,
    has_main_web_app: false,
  },
  state: {},
};

const messageToOtherUser = {
  update: {
    update_id: 9214912,
    message: {
      message_id: 20,
      from: {
        id: 886363509,
        is_bot: false,
        first_name: "Вадим",
        last_name: "Безсмертний",
        username: "VadymBezsmertnyi",
        language_code: "uk",
      },
      chat: {
        id: -4896561350,
        title: "Test group",
        type: "group",
        all_members_are_administrators: true,
        accepted_gift_types: {
          unlimited_gifts: false,
          limited_gifts: false,
          unique_gifts: false,
          premium_subscription: false,
        },
      },
      date: 1754927397,
      text: "Test",
    },
  },
  telegram: {
    token: "",
    options: {
      apiRoot: "https://api.telegram.org",
      apiMode: "bot",
      webhookReply: true,
      agent: {
        _events: {},
        _eventsCount: 2,
        defaultPort: 443,
        protocol: "https:",
        options: {
          keepAlive: true,
          keepAliveMsecs: 10000,
          noDelay: true,
          path: null,
        },
        requests: {},
        sockets: {},
        keepAliveMsecs: 10000,
        keepAlive: true,
        maxSockets: null,
        maxFreeSockets: 256,
        scheduling: "lifo",
        maxTotalSockets: null,
        totalSocketCount: 1,
        maxCachedSessions: 100,
      },
      testEnv: false,
    },
  },
  botInfo: {
    id: 7691627975,
    is_bot: true,
    first_name: "TeleGate Auth Bot",
    username: "TeleGateAuthBot",
    can_join_groups: true,
    can_read_all_group_messages: true,
    supports_inline_queries: false,
    can_connect_to_business: false,
    has_main_web_app: false,
  },
  state: {},
};

const messageToBot = {
  update: {
    update_id: 9214913,
    message: {
      message_id: 21,
      from: {
        id: 886363509,
        is_bot: false,
        first_name: "Вадим",
        last_name: "Безсмертний",
        username: "VadymBezsmertnyi",
        language_code: "uk",
      },
      chat: {
        id: -4896561350,
        title: "Test group",
        type: "group",
        all_members_are_administrators: true,
        accepted_gift_types: {
          unlimited_gifts: false,
          limited_gifts: false,
          unique_gifts: false,
          premium_subscription: false,
        },
      },
      date: 1754927423,
      reply_to_message: {
        message_id: 18,
        from: {
          id: 7691627975,
          is_bot: true,
          first_name: "TeleGate Auth Bot",
          username: "TeleGateAuthBot",
        },
        chat: {
          id: -4896561350,
          title: "Test group",
          type: "group",
          all_members_are_administrators: true,
          accepted_gift_types: {
            unlimited_gifts: false,
            limited_gifts: false,
            unique_gifts: false,
            premium_subscription: false,
          },
        },
        date: 1754927273,
        text: "Привіт! Я підключився до групи 🚀",
      },
      text: "Hi",
    },
  },
  telegram: {
    token: "",
    options: {
      apiRoot: "https://api.telegram.org",
      apiMode: "bot",
      webhookReply: true,
      agent: {
        _events: {},
        _eventsCount: 2,
        defaultPort: 443,
        protocol: "https:",
        options: {
          keepAlive: true,
          keepAliveMsecs: 10000,
          noDelay: true,
          path: null,
        },
        requests: {},
        sockets: {},
        keepAliveMsecs: 10000,
        keepAlive: true,
        maxSockets: null,
        maxFreeSockets: 256,
        scheduling: "lifo",
        maxTotalSockets: null,
        totalSocketCount: 1,
        maxCachedSessions: 100,
      },
      testEnv: false,
    },
  },
  botInfo: {
    id: 7691627975,
    is_bot: true,
    first_name: "TeleGate Auth Bot",
    username: "TeleGateAuthBot",
    can_join_groups: true,
    can_read_all_group_messages: true,
    supports_inline_queries: false,
    can_connect_to_business: false,
    has_main_web_app: false,
  },
  state: {},
};
